apiVersion: v1
kind: Service
metadata:
  name: {{ template "generic-auth-server.name" . }}
  namespace: {{ template "kyverno.lib.namespace" . }}
  labels:
    {{- include "generic-auth-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: auth
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: auth
    {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  - name: webhook
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "generic-auth-server.labels.selector" . | nindent 4 }}
