{{- if .Values.certificates.static -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "generic-auth-server.name" . }}
  namespace: {{ template "kyverno.lib.namespace" . }}
  labels:
    {{- include "generic-auth-server.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.certificates.static.crt | b64enc }}
  tls.key: {{ .Values.certificates.static.key | b64enc }}
{{- end }}
